[package]
name = "os"
version = "0.1.0"
authors = ["ZhouHr <zhr207@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
sbi-rt = { version = "0.0.3", features = ["legacy"] }
